version: '3.8'

services:
  db:
    container_name: 'tabete_db'
    image: mysql:5.7.31
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - "33006:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    command: --innodb-use-native-aio=0
  app:
    container_name: 'tabete_app'
    build:
      context: .
      args:
        ASSETS_PRECOMPILE: 'false'
    environment:
      RAILS_ENV: development
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: db
      DB_DATABASE: tabete_development
      CLIENT_HOST: localhost
    command: bundle exec rails s -b 0.0.0.0
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - tmp:/app/tmp
      - public:/app/public
    links:
      - db
    ports:
      - 3000:3000
volumes:
  mysql_data:
  bundle:
  tmp:
  public: