name: scheduled_gem_update

on: 
  schedule:
   - cron: 0 4 * * 6

jobs:
  bundle_update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout dev
        uses: actions/checkout@v2
      - name: Create new Branch
        env:
          TZ: "Asia/Tokyo"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE=`date +"%Y%m%d"`
          BRANCH_NAME="feature/gem-upgrade_$DATE"
          git checkout -b "$BRANCH_NAME"
      - name: Set up Ruby 2.6
        # actions/checkoutリポジトリのaction.ymlを利用する
        uses: actions/setup-ruby@v1 # https://github.com/actions/setup-ruby/blob/master/action.yml
        with:
          ruby-version: 2.6.x
      - name: bundle update
        run: |
          gem install bundler
          cd server
          bundle update
      - name: commit changes
        run: |
          git config user.name perpouh
          git config user.email perpouh@gmail.com
          cd server
          DATE=`date +"%Y%m%d"`
          git add Gemfile.lock
          git commit -m "bundle update $DATE"
          git push origin "feature/gem-upgrade_$DATE"
      - name: create PR
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          hub pull-request -b master -m "[Scheduled]gem_update to develop"