name: scheduled_gem_update

on: 
   - workflow_dispatch

jobs:
  bundle_update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout dev
        uses: actions/checkout@v2
      - name: pull request on bundle update
        uses: perpouh/pull-request-on-bundle-update@v1.0.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_user_name: perpouh
          git_email: perpouh@gmail.com
          target_branch: develop

